# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9b27d0e7e49b94027ba12644673c09dc4904ac52392fe33652454ea9e5cdb65699bc680f7636a45f5ec830d2eba476b4f9788f8f4a59dbafa05b58d018060cf5

test:
  secret_key_base: 9d0d80a9a5f7fa057f804f6d05161570f92323c947ea3cf23285954c9c4cf403e31813e3201dae58d5cafbe0da1eb84c032480819e0f4ad52872c7c6c4cadfa7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
